//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrialStatusApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trial
    {
        public Nullable<System.DateTime> RULE_600 { get; set; }
        public string BAIL_STATUS { get; set; }
        public string UNIT { get; set; }
        public string POLICE_DEPARTMENT { get; set; }
        public string AFFIANT { get; set; }
        public string CASE_STATUS { get; set; }
        public string CASE_NUMBER { get; set; }
        public string DEFENDANT_NAME { get; set; }
        public string DEFENSE_ATTORNEY { get; set; }
        public string PROSECUTOR { get; set; }
        public string DURATION { get; set; }
        public string DATE_CERTAIN { get; set; }
        public string JUDGE_CERTAIN { get; set; }
        public string JUDGE { get; set; }
        public string CONSOLIDATED_CASES { get; set; }
        public string JUDGES_PRECLUDED___REASON { get; set; }
        public string CW_DEF_PRECLUDED_DATES__MM_DD_YY____REASON { get; set; }
        public string C_1_HOUR_NOTICE___REASON { get; set; }
        public string MISCNOTES { get; set; }
        public System.Guid ID { get; set; }
    }
}
